// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/route/route.proto

package route

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteService_SelectChannel_FullMethodName = "/route.RouteService/SelectChannel"
	RouteService_SyncChannels_FullMethodName  = "/route.RouteService/SyncChannels"
	RouteService_HealthCheck_FullMethodName   = "/route.RouteService/HealthCheck"
)

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouteService 智能路由服务：token-factory 调用此服务获取渠道排序建议。
type RouteServiceClient interface {
	// SelectChannel 根据模型、分组和候选渠道返回排序后的渠道 ID 列表。
	SelectChannel(ctx context.Context, in *SelectChannelRequest, opts ...grpc.CallOption) (*SelectChannelResponse, error)
	// SyncChannels token-factory 将当前渠道快照推送给 TokenFactory（或 TokenFactory 拉取）。
	SyncChannels(ctx context.Context, in *SyncChannelsRequest, opts ...grpc.CallOption) (*SyncChannelsResponse, error)
	// HealthCheck 简单的健康检查。
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type routeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) SelectChannel(ctx context.Context, in *SelectChannelRequest, opts ...grpc.CallOption) (*SelectChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectChannelResponse)
	err := c.cc.Invoke(ctx, RouteService_SelectChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) SyncChannels(ctx context.Context, in *SyncChannelsRequest, opts ...grpc.CallOption) (*SyncChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncChannelsResponse)
	err := c.cc.Invoke(ctx, RouteService_SyncChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RouteService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServiceServer is the server API for RouteService service.
// All implementations must embed UnimplementedRouteServiceServer
// for forward compatibility.
//
// RouteService 智能路由服务：token-factory 调用此服务获取渠道排序建议。
type RouteServiceServer interface {
	// SelectChannel 根据模型、分组和候选渠道返回排序后的渠道 ID 列表。
	SelectChannel(context.Context, *SelectChannelRequest) (*SelectChannelResponse, error)
	// SyncChannels token-factory 将当前渠道快照推送给 TokenFactory（或 TokenFactory 拉取）。
	SyncChannels(context.Context, *SyncChannelsRequest) (*SyncChannelsResponse, error)
	// HealthCheck 简单的健康检查。
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRouteServiceServer()
}

// UnimplementedRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteServiceServer struct{}

func (UnimplementedRouteServiceServer) SelectChannel(context.Context, *SelectChannelRequest) (*SelectChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectChannel not implemented")
}
func (UnimplementedRouteServiceServer) SyncChannels(context.Context, *SyncChannelsRequest) (*SyncChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncChannels not implemented")
}
func (UnimplementedRouteServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRouteServiceServer) mustEmbedUnimplementedRouteServiceServer() {}
func (UnimplementedRouteServiceServer) testEmbeddedByValue()                      {}

// UnsafeRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServiceServer will
// result in compilation errors.
type UnsafeRouteServiceServer interface {
	mustEmbedUnimplementedRouteServiceServer()
}

func RegisterRouteServiceServer(s grpc.ServiceRegistrar, srv RouteServiceServer) {
	// If the following call panics, it indicates UnimplementedRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteService_ServiceDesc, srv)
}

func _RouteService_SelectChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).SelectChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_SelectChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).SelectChannel(ctx, req.(*SelectChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_SyncChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).SyncChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_SyncChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).SyncChannels(ctx, req.(*SyncChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteService_ServiceDesc is the grpc.ServiceDesc for RouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "route.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectChannel",
			Handler:    _RouteService_SelectChannel_Handler,
		},
		{
			MethodName: "SyncChannels",
			Handler:    _RouteService_SyncChannels_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RouteService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/route/route.proto",
}
