// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/route/route.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"` // token-factory 的逗号分隔 group，如 "default,vip"
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRole      int32                  `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"` // 角色: 1=common, 10=admin, 100=root
	TokenKey      string                 `protobuf:"bytes,5,opt,name=token_key,json=tokenKey,proto3" json:"token_key,omitempty"`  // 脱敏后的 token key 前缀，用于日志
	Candidates    []*ChannelCandidate    `protobuf:"bytes,6,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectChannelRequest) Reset() {
	*x = SelectChannelRequest{}
	mi := &file_proto_route_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectChannelRequest) ProtoMessage() {}

func (x *SelectChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectChannelRequest.ProtoReflect.Descriptor instead.
func (*SelectChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{0}
}

func (x *SelectChannelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SelectChannelRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SelectChannelRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SelectChannelRequest) GetUserRole() int32 {
	if x != nil {
		return x.UserRole
	}
	return 0
}

func (x *SelectChannelRequest) GetTokenKey() string {
	if x != nil {
		return x.TokenKey
	}
	return ""
}

func (x *SelectChannelRequest) GetCandidates() []*ChannelCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ChannelCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChannelType   int32                  `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"` // 渠道类型常量（1=OpenAI, 3=Azure, 等）
	Models        string                 `protobuf:"bytes,4,opt,name=models,proto3" json:"models,omitempty"`                               // 逗号分隔的模型列表
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`                                 // 逗号分隔的 group
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        int32                  `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`                                       // 该渠道该模型的单价（可选）
	Healthy       bool                   `protobuf:"varint,10,opt,name=healthy,proto3" json:"healthy,omitempty"`                                   // 是否健康
	LatencyP50    float64                `protobuf:"fixed64,11,opt,name=latency_p50,json=latencyP50,proto3" json:"latency_p50,omitempty"`          // P50 延迟（秒），可选
	ThroughputTps float64                `protobuf:"fixed64,12,opt,name=throughput_tps,json=throughputTps,proto3" json:"throughput_tps,omitempty"` // 吞吐量，可选
	ProviderSlug  string                 `protobuf:"bytes,13,opt,name=provider_slug,json=providerSlug,proto3" json:"provider_slug,omitempty"`      // 供应商标识，如 openai/anthropic
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCandidate) Reset() {
	*x = ChannelCandidate{}
	mi := &file_proto_route_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCandidate) ProtoMessage() {}

func (x *ChannelCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCandidate.ProtoReflect.Descriptor instead.
func (*ChannelCandidate) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelCandidate) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelCandidate) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelCandidate) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

func (x *ChannelCandidate) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *ChannelCandidate) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChannelCandidate) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelCandidate) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ChannelCandidate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelCandidate) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ChannelCandidate) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ChannelCandidate) GetLatencyP50() float64 {
	if x != nil {
		return x.LatencyP50
	}
	return 0
}

func (x *ChannelCandidate) GetThroughputTps() float64 {
	if x != nil {
		return x.ThroughputTps
	}
	return 0
}

func (x *ChannelCandidate) GetProviderSlug() string {
	if x != nil {
		return x.ProviderSlug
	}
	return ""
}

type SelectChannelResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderedChannelIds []int32                `protobuf:"varint,1,rep,packed,name=ordered_channel_ids,json=orderedChannelIds,proto3" json:"ordered_channel_ids,omitempty"` // 排序后的渠道 ID 列表
	Strategy          string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                                      // 使用的策略名，如 weight_priority/price_lowest 等
	PolicyName        string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`                                // 命中的 RoutePolicy 名称
	Fallback          bool                   `protobuf:"varint,4,opt,name=fallback,proto3" json:"fallback,omitempty"`                                                     // 是否回退到默认策略（未匹配到策略）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SelectChannelResponse) Reset() {
	*x = SelectChannelResponse{}
	mi := &file_proto_route_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectChannelResponse) ProtoMessage() {}

func (x *SelectChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectChannelResponse.ProtoReflect.Descriptor instead.
func (*SelectChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{2}
}

func (x *SelectChannelResponse) GetOrderedChannelIds() []int32 {
	if x != nil {
		return x.OrderedChannelIds
	}
	return nil
}

func (x *SelectChannelResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SelectChannelResponse) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *SelectChannelResponse) GetFallback() bool {
	if x != nil {
		return x.Fallback
	}
	return false
}

type SyncChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelSnapshot     `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	SyncTimestamp int64                  `protobuf:"varint,2,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChannelsRequest) Reset() {
	*x = SyncChannelsRequest{}
	mi := &file_proto_route_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChannelsRequest) ProtoMessage() {}

func (x *SyncChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChannelsRequest.ProtoReflect.Descriptor instead.
func (*SyncChannelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{3}
}

func (x *SyncChannelsRequest) GetChannels() []*ChannelSnapshot {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SyncChannelsRequest) GetSyncTimestamp() int64 {
	if x != nil {
		return x.SyncTimestamp
	}
	return 0
}

type ChannelSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                  int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Models                string                 `protobuf:"bytes,4,opt,name=models,proto3" json:"models,omitempty"` // 逗号分隔
	Group                 string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`   // 逗号分隔
	Status                int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Priority              int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight                int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	BaseUrl               string                 `protobuf:"bytes,9,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Balance               float64                `protobuf:"fixed64,10,opt,name=balance,proto3" json:"balance,omitempty"`
	ChannelNo             string                 `protobuf:"bytes,11,opt,name=channel_no,json=channelNo,proto3" json:"channel_no,omitempty"`
	SupplierApplicationId int32                  `protobuf:"varint,12,opt,name=supplier_application_id,json=supplierApplicationId,proto3" json:"supplier_application_id,omitempty"`
	SupplierAlias         string                 `protobuf:"bytes,13,opt,name=supplier_alias,json=supplierAlias,proto3" json:"supplier_alias,omitempty"`
	ProviderSlug          string                 `protobuf:"bytes,14,opt,name=provider_slug,json=providerSlug,proto3" json:"provider_slug,omitempty"`
	PriceDiscountPercent  float64                `protobuf:"fixed64,15,opt,name=price_discount_percent,json=priceDiscountPercent,proto3" json:"price_discount_percent,omitempty"`
	MarkupDiscountRate    float64                `protobuf:"fixed64,16,opt,name=markup_discount_rate,json=markupDiscountRate,proto3" json:"markup_discount_rate,omitempty"`
	ModelMapping          string                 `protobuf:"bytes,17,opt,name=model_mapping,json=modelMapping,proto3" json:"model_mapping,omitempty"` // JSON
	// model_prices 每个模型的最终单价（已含成本 / 加价折扣），key=模型名。
	// 用于 TokenFactory 价格优模式展示与排序。
	ModelPrices   map[string]float64 `protobuf:"bytes,18,rep,name=model_prices,json=modelPrices,proto3" json:"model_prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSnapshot) Reset() {
	*x = ChannelSnapshot{}
	mi := &file_proto_route_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSnapshot) ProtoMessage() {}

func (x *ChannelSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSnapshot.ProtoReflect.Descriptor instead.
func (*ChannelSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelSnapshot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelSnapshot) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChannelSnapshot) GetModels() string {
	if x != nil {
		return x.Models
	}
	return ""
}

func (x *ChannelSnapshot) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ChannelSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelSnapshot) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelSnapshot) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ChannelSnapshot) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ChannelSnapshot) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ChannelSnapshot) GetChannelNo() string {
	if x != nil {
		return x.ChannelNo
	}
	return ""
}

func (x *ChannelSnapshot) GetSupplierApplicationId() int32 {
	if x != nil {
		return x.SupplierApplicationId
	}
	return 0
}

func (x *ChannelSnapshot) GetSupplierAlias() string {
	if x != nil {
		return x.SupplierAlias
	}
	return ""
}

func (x *ChannelSnapshot) GetProviderSlug() string {
	if x != nil {
		return x.ProviderSlug
	}
	return ""
}

func (x *ChannelSnapshot) GetPriceDiscountPercent() float64 {
	if x != nil {
		return x.PriceDiscountPercent
	}
	return 0
}

func (x *ChannelSnapshot) GetMarkupDiscountRate() float64 {
	if x != nil {
		return x.MarkupDiscountRate
	}
	return 0
}

func (x *ChannelSnapshot) GetModelMapping() string {
	if x != nil {
		return x.ModelMapping
	}
	return ""
}

func (x *ChannelSnapshot) GetModelPrices() map[string]float64 {
	if x != nil {
		return x.ModelPrices
	}
	return nil
}

type SyncChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChannelsResponse) Reset() {
	*x = SyncChannelsResponse{}
	mi := &file_proto_route_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChannelsResponse) ProtoMessage() {}

func (x *SyncChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChannelsResponse.ProtoReflect.Descriptor instead.
func (*SyncChannelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{5}
}

func (x *SyncChannelsResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_route_route_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_route_route_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_route_route_proto protoreflect.FileDescriptor

const file_proto_route_route_proto_rawDesc = "" +
	"\n" +
	"\x17proto/route/route.proto\x12\x05route\"\xce\x01\n" +
	"\x14SelectChannelRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tuser_role\x18\x04 \x01(\x05R\buserRole\x12\x1b\n" +
	"\ttoken_key\x18\x05 \x01(\tR\btokenKey\x127\n" +
	"\n" +
	"candidates\x18\x06 \x03(\v2\x17.route.ChannelCandidateR\n" +
	"candidates\"\x8e\x03\n" +
	"\x10ChannelCandidate\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12!\n" +
	"\fchannel_type\x18\x03 \x01(\x05R\vchannelType\x12\x16\n" +
	"\x06models\x18\x04 \x01(\tR\x06models\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\a \x01(\x05R\x06weight\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x18\n" +
	"\ahealthy\x18\n" +
	" \x01(\bR\ahealthy\x12\x1f\n" +
	"\vlatency_p50\x18\v \x01(\x01R\n" +
	"latencyP50\x12%\n" +
	"\x0ethroughput_tps\x18\f \x01(\x01R\rthroughputTps\x12#\n" +
	"\rprovider_slug\x18\r \x01(\tR\fproviderSlug\"\xa0\x01\n" +
	"\x15SelectChannelResponse\x12.\n" +
	"\x13ordered_channel_ids\x18\x01 \x03(\x05R\x11orderedChannelIds\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\x12\x1a\n" +
	"\bfallback\x18\x04 \x01(\bR\bfallback\"p\n" +
	"\x13SyncChannelsRequest\x122\n" +
	"\bchannels\x18\x01 \x03(\v2\x16.route.ChannelSnapshotR\bchannels\x12%\n" +
	"\x0esync_timestamp\x18\x02 \x01(\x03R\rsyncTimestamp\"\xb4\x05\n" +
	"\x0fChannelSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06models\x18\x04 \x01(\tR\x06models\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x19\n" +
	"\bbase_url\x18\t \x01(\tR\abaseUrl\x12\x18\n" +
	"\abalance\x18\n" +
	" \x01(\x01R\abalance\x12\x1d\n" +
	"\n" +
	"channel_no\x18\v \x01(\tR\tchannelNo\x126\n" +
	"\x17supplier_application_id\x18\f \x01(\x05R\x15supplierApplicationId\x12%\n" +
	"\x0esupplier_alias\x18\r \x01(\tR\rsupplierAlias\x12#\n" +
	"\rprovider_slug\x18\x0e \x01(\tR\fproviderSlug\x124\n" +
	"\x16price_discount_percent\x18\x0f \x01(\x01R\x14priceDiscountPercent\x120\n" +
	"\x14markup_discount_rate\x18\x10 \x01(\x01R\x12markupDiscountRate\x12#\n" +
	"\rmodel_mapping\x18\x11 \x01(\tR\fmodelMapping\x12J\n" +
	"\fmodel_prices\x18\x12 \x03(\v2'.route.ChannelSnapshot.ModelPricesEntryR\vmodelPrices\x1a>\n" +
	"\x10ModelPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"9\n" +
	"\x14SyncChannelsResponse\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xe9\x01\n" +
	"\fRouteService\x12J\n" +
	"\rSelectChannel\x12\x1b.route.SelectChannelRequest\x1a\x1c.route.SelectChannelResponse\x12G\n" +
	"\fSyncChannels\x12\x1a.route.SyncChannelsRequest\x1a\x1b.route.SyncChannelsResponse\x12D\n" +
	"\vHealthCheck\x12\x19.route.HealthCheckRequest\x1a\x1a.route.HealthCheckResponseB,Z*github.com/QuantumNous/new-api/proto/routeb\x06proto3"

var (
	file_proto_route_route_proto_rawDescOnce sync.Once
	file_proto_route_route_proto_rawDescData []byte
)

func file_proto_route_route_proto_rawDescGZIP() []byte {
	file_proto_route_route_proto_rawDescOnce.Do(func() {
		file_proto_route_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_route_proto_rawDesc), len(file_proto_route_route_proto_rawDesc)))
	})
	return file_proto_route_route_proto_rawDescData
}

var file_proto_route_route_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_route_route_proto_goTypes = []any{
	(*SelectChannelRequest)(nil),  // 0: route.SelectChannelRequest
	(*ChannelCandidate)(nil),      // 1: route.ChannelCandidate
	(*SelectChannelResponse)(nil), // 2: route.SelectChannelResponse
	(*SyncChannelsRequest)(nil),   // 3: route.SyncChannelsRequest
	(*ChannelSnapshot)(nil),       // 4: route.ChannelSnapshot
	(*SyncChannelsResponse)(nil),  // 5: route.SyncChannelsResponse
	(*HealthCheckRequest)(nil),    // 6: route.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 7: route.HealthCheckResponse
	nil,                           // 8: route.ChannelSnapshot.ModelPricesEntry
}
var file_proto_route_route_proto_depIdxs = []int32{
	1, // 0: route.SelectChannelRequest.candidates:type_name -> route.ChannelCandidate
	4, // 1: route.SyncChannelsRequest.channels:type_name -> route.ChannelSnapshot
	8, // 2: route.ChannelSnapshot.model_prices:type_name -> route.ChannelSnapshot.ModelPricesEntry
	0, // 3: route.RouteService.SelectChannel:input_type -> route.SelectChannelRequest
	3, // 4: route.RouteService.SyncChannels:input_type -> route.SyncChannelsRequest
	6, // 5: route.RouteService.HealthCheck:input_type -> route.HealthCheckRequest
	2, // 6: route.RouteService.SelectChannel:output_type -> route.SelectChannelResponse
	5, // 7: route.RouteService.SyncChannels:output_type -> route.SyncChannelsResponse
	7, // 8: route.RouteService.HealthCheck:output_type -> route.HealthCheckResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_route_route_proto_init() }
func file_proto_route_route_proto_init() {
	if File_proto_route_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_route_proto_rawDesc), len(file_proto_route_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_route_proto_goTypes,
		DependencyIndexes: file_proto_route_route_proto_depIdxs,
		MessageInfos:      file_proto_route_route_proto_msgTypes,
	}.Build()
	File_proto_route_route_proto = out.File
	file_proto_route_route_proto_goTypes = nil
	file_proto_route_route_proto_depIdxs = nil
}
