// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kling/v1/videos/image2video": {
            "post": {
                "description": "调用可灵AI图生视频接口，生成视频内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "可灵官方-图生视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户认证令牌 (Aeess-Token: sk-xxxx)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "图生视频请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.KlingImage2VideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态和结果",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoTaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/kling/v1/videos/image2video/{task_id}": {
            "get": {
                "description": "Query the status and result of a Kling video generation task by task ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Origin"
                ],
                "summary": "可灵任务查询--图生视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/kling/v1/videos/text2video": {
            "post": {
                "description": "调用可灵AI文生视频接口，生成视频内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "可灵文生视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户认证令牌 (Aeess-Token: sk-xxxx)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "视频生成请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.KlingText2VideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态和结果",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoTaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/kling/v1/videos/text2video/{task_id}": {
            "get": {
                "description": "Query the status and result of a Kling text-to-video generation task by task ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Origin"
                ],
                "summary": "可灵任务查询--文生视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/messages/self": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "查询当前用户站内消息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "p",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/messages/unread_count": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "获取当前用户未读站内消息数量",
                "responses": {
                    "200": {
                        "description": "success + data{unread_count}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/messages/{id}/read": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "标记当前用户消息为已读",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "消息ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success + data{updated}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/supplier/application": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SupplierAdmin"
                ],
                "summary": "管理员分页查询供应商申请",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "p",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态：0待审核 1审核通过 2审核驳回",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "普通用户提交供应商申请，提交后生成管理员待审核站内消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Supplier"
                ],
                "summary": "提交供应商入驻申请",
                "parameters": [
                    {
                        "description": "申请信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.SupplierApplicationSubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success + data{id,status}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/supplier/application/self": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Supplier"
                ],
                "summary": "查询当前用户提交的供应商申请",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "p",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态：0待审核 1审核通过 2审核驳回",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/supplier/application/{id}/review": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "任一管理员可审核一次，仅待审核状态允许处理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SupplierAdmin"
                ],
                "summary": "管理员审核供应商申请",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "申请ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "审核信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.SupplierApplicationReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success + data{id,status}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/video/generations": {
            "post": {
                "description": "调用视频生成接口生成视频\n支持多种视频生成服务：\n- 可灵AI (Kling): https://app.klingai.com/cn/dev/document-api/apiReference/commonInfo\n- 即梦 (Jimeng): https://www.volcengine.com/docs/85621/1538636",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "生成视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户认证令牌 (Aeess-Token: sk-xxxx)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "视频生成请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VideoRequest"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/video/generations/{task_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据任务ID查询视频生成任务的状态和结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "查询视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态和结果",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoTaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.KlingCameraConfig": {
            "type": "object",
            "properties": {
                "horizontal": {
                    "type": "number",
                    "example": 2.5
                },
                "pan": {
                    "type": "number",
                    "example": 0
                },
                "roll": {
                    "type": "number",
                    "example": 0
                },
                "tilt": {
                    "type": "number",
                    "example": 0
                },
                "vertical": {
                    "type": "number",
                    "example": 0
                },
                "zoom": {
                    "type": "number",
                    "example": 0
                }
            }
        },
        "controller.KlingCameraControl": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/controller.KlingCameraConfig"
                },
                "type": {
                    "type": "string",
                    "example": "simple"
                }
            }
        },
        "controller.KlingImage2VideoRequest": {
            "type": "object",
            "required": [
                "image"
            ],
            "properties": {
                "aspect_ratio": {
                    "type": "string",
                    "example": "16:9"
                },
                "callback_url": {
                    "type": "string",
                    "example": "https://your.domain/callback"
                },
                "camera_control": {
                    "$ref": "#/definitions/controller.KlingCameraControl"
                },
                "cfg_scale": {
                    "type": "number",
                    "example": 0.7
                },
                "duration": {
                    "type": "string",
                    "example": "5"
                },
                "external_task_id": {
                    "type": "string",
                    "example": "custom-task-002"
                },
                "image": {
                    "type": "string",
                    "example": "https://h2.inkwai.com/bs2/upload-ylab-stunt/se/ai_portal_queue_mmu_image_upscale_aiweb/3214b798-e1b4-4b00-b7af-72b5b0417420_raw_image_0.jpg"
                },
                "mode": {
                    "type": "string",
                    "example": "std"
                },
                "model_name": {
                    "type": "string",
                    "example": "kling-v2-master"
                },
                "negative_prompt": {
                    "type": "string",
                    "example": "blurry, low quality"
                },
                "prompt": {
                    "type": "string",
                    "example": "A cat playing piano in the garden"
                }
            }
        },
        "controller.KlingText2VideoRequest": {
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "aspect_ratio": {
                    "type": "string",
                    "example": "16:9"
                },
                "callback_url": {
                    "type": "string",
                    "example": "https://your.domain/callback"
                },
                "camera_control": {
                    "$ref": "#/definitions/controller.KlingCameraControl"
                },
                "cfg_scale": {
                    "type": "number",
                    "example": 0.7
                },
                "duration": {
                    "type": "string",
                    "example": "5"
                },
                "external_task_id": {
                    "type": "string",
                    "example": "custom-task-001"
                },
                "mode": {
                    "type": "string",
                    "example": "std"
                },
                "model_name": {
                    "type": "string",
                    "example": "kling-v1"
                },
                "negative_prompt": {
                    "type": "string",
                    "example": "blurry, low quality"
                },
                "prompt": {
                    "type": "string",
                    "example": "A cat playing piano in the garden"
                }
            }
        },
        "controller.SupplierApplicationReviewRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "controller.SupplierApplicationSubmitRequest": {
            "type": "object",
            "properties": {
                "business_license_url": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "company_size": {
                    "type": "string"
                },
                "contact_mobile": {
                    "type": "string"
                },
                "contact_name": {
                    "type": "string"
                },
                "contact_wechat": {
                    "type": "string"
                },
                "credit_code": {
                    "type": "string"
                },
                "legal_representative": {
                    "type": "string"
                }
            }
        },
        "dto.VideoRequest": {
            "type": "object",
            "properties": {
                "duration": {
                    "description": "Video duration (seconds)",
                    "type": "number",
                    "example": 5
                },
                "fps": {
                    "description": "Video frame rate",
                    "type": "integer",
                    "example": 30
                },
                "height": {
                    "description": "Video height",
                    "type": "integer",
                    "example": 512
                },
                "image": {
                    "description": "Image input (URL/Base64)",
                    "type": "string",
                    "example": "https://h2.inkwai.com/bs2/upload-ylab-stunt/se/ai_portal_queue_mmu_image_upscale_aiweb/3214b798-e1b4-4b00-b7af-72b5b0417420_raw_image_0.jpg"
                },
                "metadata": {
                    "description": "Vendor-specific/custom params (e.g. negative_prompt, style, quality_level, etc.)",
                    "type": "object",
                    "additionalProperties": {}
                },
                "model": {
                    "description": "Model/style ID",
                    "type": "string",
                    "example": "kling-v1"
                },
                "n": {
                    "description": "Number of videos to generate",
                    "type": "integer",
                    "example": 1
                },
                "prompt": {
                    "description": "Text prompt",
                    "type": "string",
                    "example": "宇航员站起身走了"
                },
                "response_format": {
                    "description": "Response format",
                    "type": "string",
                    "example": "url"
                },
                "seed": {
                    "description": "Random seed",
                    "type": "integer",
                    "example": 20231234
                },
                "user": {
                    "description": "User identifier",
                    "type": "string",
                    "example": "user-1234"
                },
                "width": {
                    "description": "Video width",
                    "type": "integer",
                    "example": 512
                }
            }
        },
        "dto.VideoTaskError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.VideoTaskMetadata": {
            "type": "object",
            "properties": {
                "duration": {
                    "description": "实际生成的视频时长",
                    "type": "number",
                    "example": 5
                },
                "fps": {
                    "description": "实际帧率",
                    "type": "integer",
                    "example": 30
                },
                "height": {
                    "description": "实际高度",
                    "type": "integer",
                    "example": 512
                },
                "seed": {
                    "description": "使用的随机种子",
                    "type": "integer",
                    "example": 20231234
                },
                "width": {
                    "description": "实际宽度",
                    "type": "integer",
                    "example": 512
                }
            }
        },
        "dto.VideoTaskResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "错误信息（失败时）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.VideoTaskError"
                        }
                    ]
                },
                "format": {
                    "description": "视频格式",
                    "type": "string",
                    "example": "mp4"
                },
                "metadata": {
                    "description": "结果元数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.VideoTaskMetadata"
                        }
                    ]
                },
                "status": {
                    "description": "任务状态",
                    "type": "string",
                    "example": "succeeded"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "abcd1234efgh"
                },
                "url": {
                    "description": "视频资源URL（成功时）",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "TokenFactory API",
	Description:      "TokenFactory backend API documentation powered by swaggo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
